services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
