spring:
  config:
    import: optional:file:.env[.properties]

  pagination:
    max-page-size: ${PAGINATION_MAX_PAGE_SIZE}

  application:
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: ${JWT_EXPIRATION}
        refresh-token:
          expiration: ${JWT_REFRESH_EXPIRATION}

  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect