package com.benjamerc.spring_security_course.shared.exception;

public enum ErrorCode {

    USER_NOT_FOUND,
    VALIDATION_ERROR,
    REFRESH_TOKEN_NOT_FOUND,
    INTERNAL_ERROR,
    UNEXPECTED_ERROR,
    USERNAME_ALREADY_EXISTS,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_REVOKED,
    ACCESS_TOKEN_EXPIRED,
    ACCESS_TOKEN_INVALID_SIGNATURE,
    ACCESS_TOKEN_INVALID,
    HASHING_EXCEPTION,
    DATABASE_ERROR
}
